---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build wpg
    commands:
    - mkdir -p /tmp/cache/node_modules /tmp/cache/go
    - buildah bud --volume /tmp/cache/node_modules:/home/wpg/assets/static/node_modules:z --volume /tmp/cache/go:/root/go:z --volume /var/cache/dnf:/var/cache/dnf:z -f scripts/Dockerfiles/build -t wpg-build:latest .
    - podman run --volume /tmp/cache/node_modules:/home/wpg/assets/static/node_modules:z --volume /tmp/cache/go:/root/go:z --volume /var/cache/dnf:/var/cache/dnf:z --privileged -ti wpg-build:latest
